src/Entity/Season.php
<?php

namespace App\Entity;

use App\Repository\SeasonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SeasonRepository::class)]
class Season
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * @var Collection<int, Week>
     */
    #[ORM\OneToMany(targetEntity: Week::class, mappedBy: 'season', orphanRemoval: true, cascade: ['persist', 'remove'])]
    private Collection $weeks;

    #[ORM\Column(length: 16)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $datetime = null;


    #[ORM\Column]
    private int $finishedGames = 0;

    public function __construct()
    {
        $this->weeks = new ArrayCollection();
        $this->datetime = new \DateTime();
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getWeek(int $weekId): ?Week
    {
        return $this->weeks[$weekId] ?? null;
    }
    
    /**
     * @return Collection<int, Week>
     */
    public function getWeeks(): Collection
    {
        return $this->weeks;
    }

    public function addWeek(Week $week): static
    {
        if (!$this->weeks->contains($week)) {
            $this->weeks->add($week);
            $week->setSeason($this);
        }

        return $this;
    }

    public function removeWeek(Week $week): static
    {
        if ($this->weeks->removeElement($week)) {
            // set the owning side to null (unless already changed)
            if ($week->getSeason() === $this) {
                $week->setSeason(null);
            }
        }

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }
    
    public function getTeams(): array{
        $teams = [];
        foreach($this->weeks as $week){
            foreach($week->getGames() as $game){
                if(!isset($teams[$game->getHomeTeam()->getId()])){
                    $teams[$game->getHomeTeam()->getId()] = $game->getHomeTeam();
                }
            }
        }
        return $teams;
    }

    public function getCountOfCames(): int{
        $games = 0;
        foreach($this->weeks as $week){
            $games += count($week->getGames());
        }
        return $games;
    }
    
    public function getDatetime(): ?\DateTimeInterface
    {
        return $this->datetime;
    }

    public function setDatetime(\DateTimeInterface $datetime): static
    {
        $this->datetime = $datetime;

        return $this;
    }

    public function getFinishedGames(): ?int
    {
        return $this->finishedGames;
    }

    public function increaseFinishedGames(): static
    {
        $this->finishedGames += 1;

        return $this;
    }
    
    public function isSeasonFinished():bool{
        return $this->finishedGames === $this->getCountOfCames();
    }
}

src/Controller/LeagueController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Service\LeagueService;
use Symfony\Component\HttpFoundation\Request;
use App\Form\SimulationType;
use Symfony\Component\HttpFoundation\JsonResponse;
use App\Service\MatchNavService;

class LeagueController extends AbstractController
{
    private LeagueService $_leagueService;
    private MatchNavService $_matchNavService;
    
    public function __construct(
        LeagueService $_leagueService ,
        MatchNavService $matchNavService
    ) {
        $this->_leagueService = $_leagueService;
        $this->_matchNavService = $matchNavService;
    }
    
    #[Route('/league/playAll/{id}', name: 'simulate_season', requirements: ['id' => '\d+', 'week' => '\d+'])]
    public function simulateAll(int $id,Request $request): Response
    {
        $season = $this->_leagueService->getSeasonById($id);
        if(!$season){
            throw $this->createNotFoundException('Page not found.');
        }
        $refresh = $request->get('refresh',false);
        $weekResults = $this->_leagueService->playAll($season,$refresh);
        return $this->render('league/simulate_all.html.twig', [
            'weekResults' => $weekResults,
            'seasonId' => $id
        ]);            
    }
    
    #[Route('/getData/{id}/{week}', name: 'get_week_data', requirements: ['id' => '\d+', 'week' => '\d+'])]
    public function getData(int $id,Request $request,int $week = 0): Response
    {
        $season = $this->_leagueService->getSeasonById($id);
        if(!$season){
            throw $this->createNotFoundException('Page not found.');
        } 
        try{
            $refresh = $request->get('refresh',false);
            $weekResult = $this->_leagueService->playWeek($season, $week,$refresh);
        }catch(\InvalidArgumentException $invalidArgument){
            throw $this->createNotFoundException('Page not found.');
        }
        return $this->render('league/_score.html.twig', [
            'weekNum' => $week,
            'nav' => $this->_matchNavService->buildNavMenu($season, $week),
            'weekResult' => $weekResult,
            'seasonId' => $id,
        ]);
    }
    
    #[Route('/editGame', name: 'edit_game', methods: ['POST'])]
    public function editGame(Request $request): JsonResponse
    {
        $status = true;
        $message = '';
        $code = 200;
        if(!$request->get('gameId') || !$request->get('scoreType')){
            throw $this->createNotFoundException('Page not found.');
        }
        try{
            $this->_leagueService->changeGameResult($request->get('gameId'),$request->get('scoreType'),$request->get('score'));
        }catch(\InvalidArgumentException $invalidAttributeException){
            $status = false;
            $message = $invalidAttributeException->getMessage();
            $code = 400;
        }catch(\Exception $exeption){
            $status = false;
            $message = $exeption->getMessage();
            $code = 500;
        }
        return $this->json([
            'status' => $status,
            'message' => $message,
        ],$code);
    }
    
    #[Route('/simulate/{id}', name: 'simulate_week', requirements: ['id' => '\d+'])]
    public function simulate(int $id): Response
    {
        $season = $this->_leagueService->isSeasonExists($id);
        if(!$season){
            throw $this->createNotFoundException('Page not found.');
        } 
        return $this->render('league/simulate.html.twig', [
            'seasonId' => $id
        ]);
    }
    
    #[Route('/', name: 'index_league')]
    public function index(Request $request): Response
    {
        $form = $this->createForm(SimulationType::class, null);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $season = $this->_leagueService->createNewSeason($data['teams']);
            return $this->redirectToRoute('simulate_week', ['id' => $season->getId()]);
        }
        return $this->render('league/index.html.twig', [
            'form' => $form->createView(),
            'history' => $this->_leagueService->getHistory()
        ]);
    }
}

templates/league/_score.html.twig
<div class="card col-md-12 mt-2">
  <div class="card-body">
    <h5 class="card-title">{{ weekNum + 1 }}th Week match results:</h5>
    <div class="row">
        <div class="col-md-5">
            <table class="table table-striped score-table">
                <thead>
                    <tr><td colspan="7">League Table</td></tr>
                    <tr>
                        <th scope="col">Teams</th>
                        <th scope="col">PTS</th>
                        <th scope="col">P</th>
                        <th scope="col">W</th>
                        <th scope="col">D</th>
                        <th scope="col">L</th>
                        <th scope="col">GD</th>
                    </tr>
                </thead>
                <tbody>
                    {% for statistic in weekResult.teamStat %}
                        <tr>
                            <td>{{ statistic.team.name }}</td>
                            <td>{{ statistic.points }}</td>
                            <td>{{ statistic.games }}</td>
                            <td>{{ statistic.win }}</td>
                            <td>{{ statistic.draw }}</td>
                            <td>{{ statistic.loss }}</td>
                            <td>{{ statistic.diff }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-4">
            <table class="table table-striped match-result">
                <thead>
                    <tr>
                        <td colspan="3">Match Results</td>
                    </tr>
                </thead>
                <tbody>
                    {% for game in weekResult.games %}
                        <tr>
                            <td>{{ game.phomeTeam.name }}</td>
                            <td>
                                <span class="score"><a href="#" data-game-id="{{ game.id }}" data-score-type="homeScore" class="edit-result">{{ game.homeScore }}</a> - <a href="#" data-game-id="{{ game.id }}" data-score-type="guestScore" class="edit-result">{{ game.guestscore }}</a></span>
                            </td>
                            <td>{{ game.guestTeam.name }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
            <div class="col-md-3">
            <table class="table table-striped prediction">
                <thead>
                    <tr>
                        <td colspan="2">Predictions:</td>
                    </tr>
                </thead>
                <tbody>
                    {% if weekNum > 3 %}
                        {% for stat in weekResult.teamStat %}
                            <tr>
                                <td>{{ stat.team.name }}</td>
                                <td>%{{ stat.prediction }}</td>
                            </tr>
                        {% endfor %}
                    {% else %}
                            <tr>
                                <td colspan="2">Not available till 5th week.</td>
                            </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            {% if nav %}
                <p class="mt-2">
                    {% for navItem in nav %}
                        <a class="btn btn-primary page-control" href="{{ navItem.url }}">{{ navItem.label }}</a>
                    {% endfor %}
                    <a class="btn btn-primary page-control refresh-game" href="{{ path('get_week_data', {'id': seasonId,'week':weekNum, 'refresh': true}) }}">Play this week again</a>
                </p>
            {% endif %}
        </div>
    </div>
  </div>
</div>

templates/league/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}EPL Score Simulator{% endblock %}


    {% block body %}  
        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    {{ form_start(form, {'attr': {id:'new-game-form','class': 'form'}}) }}
                    <div class="form-group">
                        {{ form_label(form.teams, 'Select Teams', {'label_attr': {'class': 'control-label'}}) }}
                        {{ form_widget(form.teams, {'attr': {'class': 'form-control select2', 'multiple': 'multiple'}}) }}
                        {% if form_errors(form.teams) %}
                            <div style="display:block" class="invalid-feedback">
                                {{ form_errors(form.teams) }}
                            </div>
                        {% endif %}
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">New Game</button>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <h2>Recent games</h2>
                <table class="table table-striped recent-seasons">
                    <thead>
                        <tr>
                            <th scope="col">Simulation ID</th>
                            <th scope="col">Time of a simulation</th>
                            <th scope="col">Finished Games</th>
                            <th scope="col">All Games</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for season in history %}
                         <tr>
                             <td><a href="{{ path('simulate_week', {'id': season.id}) }}">{{ season.id }}</a></td>
                             <td>{{ season.datetime|date('d-m-Y H:i') }}</td>
                             <td>{{ season.finishedGames }}</td>
                             <td>{{ season.countOfCames }}</td>
                         </tr>
                     {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endblock %}

templates/league/simulate.html.twig
{% extends 'base.html.twig' %}
{% block title %}EPL Score Simulator{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-md-8">
            <a class="btn btn-info" href="{{ path('index_league')}}">Return</a>
        </div>
    </div>
    <div data-update-url="{{ path('edit_game')}}" data-url="{{ path('get_week_data', {'id': seasonId}) }}" id="result-table">
        
    </div>
{% endblock %}

templates/league/simulate_all.html.twig
{% for weekResult in weekResults %}
    {% set data = {
        nav: [],
        weekNum : loop.index0 + 1,
        seasonId: seasonId
    } %}

    {% include 'league/_score.html.twig' with data %}
{% endfor %}
<div class="row">
    <div class="col-md-12">
        <p class="mt-2">
            <a class="btn btn-primary page-control refresh-game" href="{{ path('simulate_season', {'id': seasonId, 'refresh': true}) }}">Play All Again</a>
        </p>
    </div>
</div>